apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |+
    worker_processes  5;
    events {
      worker_connections  4096;
    }
    http {
        server {

            root /usr/share/nginx/html/;
            index index.html;

            location /nginx_status {
              stub_status on;
              access_log  /dev/stdout;
              allow all;
            }
        }
    }
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a the Index file </h1>
    </html